#!/bin/sh
#############################################################################
##
## Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
##
## This file is part of the Qt Enterprise Embedded Scripts of the Qt
## framework.
##
## $QT_BEGIN_LICENSE$
## Commercial License Usage Only
## Licensees holding valid commercial Qt license agreements with Digia
## with an appropriate addendum covering the Qt Enterprise Embedded Scripts,
## may use this file in accordance with the terms contained in said license
## agreement.
##
## For further information use the contact form at
## http://qt.digia.com/contact-us.
##
##
## $QT_END_LICENSE$
##
#############################################################################

set -e

if [ $# -ne 1 ]; then
    echo "Usage: $0 <yocto build directory>"
    exit 1
fi

mkdir -p ${1}

DIR=$(readlink -f $(dirname $0))
BUILDDIR=$(readlink -f $1)

checkout() {
    REPO=$1
    REPODIR=${REPO##*/}
    if [ ${REPODIR} != "poky" ]; then
        REPODIR="poky/${REPODIR}"
    fi
    REF=${2%%:*}
    SHA1=${2##*:}
    if [ ! -d ${BUILDDIR}/${REPODIR} ]; then
        mkdir ${BUILDDIR}/${REPODIR}
        cd ${BUILDDIR}/${REPODIR}
        git init
        git remote add origin ${REPO} -f
        git checkout ${REF}
        git reset --hard ${SHA1}
        cd -
    fi
}

checkout git://git.yoctoproject.org/poky                "daisy:b0ce70ffa820c8b4069bdb413f7aa9db668b9428"
checkout git://git.openembedded.org/meta-openembedded   "daisy:a6dcf6265822ca1484d991d10a3042e04a960cdb"
checkout git://git.yoctoproject.org/meta-ti             "daisy:5dad1bc02dd922a6c4fa4d68f6ea9ec779cf5e66"
checkout git://git.yoctoproject.org/meta-fsl-arm        "daisy:f5bf277a5a5fba2c3b64ed7d2dbec1903d96386b"
checkout git://github.com/Freescale/meta-fsl-arm-extra  "daisy:029f535cfbc5746288c6129babb2d7679927a183"
checkout git://git.yoctoproject.org/meta-raspberrypi    "daisy:cc74bf6c1f9ab9beea52c4c75797f3ad51f72c55"
checkout git://git.toradex.com/meta-toradex             "V2.2:371ea626f29a2a12294ab6ea30e36743a9e2f78f"

if [ ! -d ${BUILDDIR}/poky/meta-b2qt ]; then
    ln -s ${DIR} ${BUILDDIR}/poky/meta-b2qt
fi

echo
echo "Yocto build system is ready"
echo "next initialize the build env for your target machine, for example:"
echo
echo "cd ${BUILDDIR}"
echo "export TEMPLATECONF=meta-b2qt/conf"
echo "export MACHINE=raspberrypi"
echo ". ./poky/oe-init-build-env build-raspberrypi"
echo
echo "and build B2Qt image with:"
echo
echo "bitbake b2qt-embedded-image"
echo
