#!/bin/sh

if [ ! -e /etc/network/interfaces.fixed ]; then
    HWADDRESS=$(cat /sys/class/net/eth0/address)
    sed -i -e 's,^#\(.*\)00:00:00:00:00:00,\1'$HWADDRESS',' /etc/network/interfaces
    touch /etc/network/interfaces.fixed
fi
