#!/bin/sh
case "$1" in
start)
    insmod $(busybox find /lib/modules/$(uname -r) -name "g_ffs.ko") idVendor=0x18d1 idProduct=0x4e26 iSerialNumber=$(hostname)
    mkdir -p /dev/usb-ffs
    chmod 770 /dev/usb-ffs
    mkdir -p /dev/usb-ffs/adb
    chmod 770 /dev/usb-ffs/adb
    mount -t functionfs adb /dev/usb-ffs/adb -o uid=0,gid=0

    /usr/bin/adbd &
    ;;
stop)
    killall adbd
    umount /dev/usb-ffs/adb
    rmmod g_ffs
    ;;
*)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
