TK1_CFLAGS             = -DWIN_INTERFACE_CUSTOM
QMAKE_LIBS_EGL         += -lEGL
QMAKE_LIBS_OPENGL_ES2  += -lGLESv2 -lEGL
QMAKE_CFLAGS           += $$TK1_CFLAGS
QMAKE_CXXFLAGS         += $$TK1_CFLAGS

QMAKE_PLATFORM         += boot2qt

QT_QPA_DEFAULT_PLATFORM = eglfs
EGLFS_DEVICE_INTEGRATION = eglfs_kms_egldevice

